### ISSUE TITLE
Convert Mining District File TIFFs to PDFs

### ISSUE THREAD

**Issue by emilyodean** [NBMG-UNR/gbssrl_students#10]
Additional note: 
Please QA each PDF as you are assembling it and make sure every page is right-side up and readable.

Copied from email: 
The UNR library scanned a bunch of mining district files for us right before the pandemic occurred, and we need to go through them and convert the files to PDFs. I’d like you to get started on this today, and just shared the Box folder with you called library_scans. 

Each folder name within is the ID of one file, which will contain multiple TIFFs (one TIFF per page). All pages should be combined into one PDF, with the exception of the cover sheet (this gets left out of the PDF). The PDF should be saved with the title the same as the ID (ex: 60004380.pdf). Then, we need to add the accessibility components to the PDFs. Don’t worry about making these perfect, but do add the title, language, and attempt to add tags. It’s ok if there are some errors – don’t spend more than 10 minutes or so on each. 

The easiest way I’ve found to get the TIFFs off of Box and into PDF format is to install the Box Drive tool, which lets you access your Box files as if they were on your file system. Then, you can just select all the TIF pages you want to convert, right click, and select “Combine Files in Acrobat.” Screenshot of this below. However you want to do it is fine with me, though. 

When you’re done with each, please upload to the “mining_district_PDFs” folder that I just made within the “Mining District File Screenshots” folder - 
https://nevada.box.com/s/lwreqrcgvin8p8xkt8k1sic652gwpcal

Let me know if you have questions! I’m also going to capture all of this in a github ticket so you can post updates there.

**Comment by madsmiller** [comment]
I was able to get through the first few. I'd say I have a fairly good understanding of the process now. Today, unfortunately, I wasn't able to get through many of them. Once I was able to get the internet working, Adobe Acrobat kept freezing and not responding. I'm going to try figure out whats going on. I might just have to delete it and reinstall it - it's very frustrating.

**Comment by emilyodean** [comment]
@madsmiller thanks for the update. I might write a script to make PDFs out of the TIFFs and just have you do the accessibility part. Acrobat is probably crashing for you because some of those TIFFs are so huge. I'll see if I can get that done and let you know.

**Comment by madsmiller** [comment]
@emilyodean Okay! That is possibly the issue. It's odd, though, because for the first few times, the program was just slow but it worked. Then the last few times I tried it just kept crashing. But like you said, maybe the last few files were just too large. Thank you!

**Comment by emilyodean** [comment]
@madsmiller I was able to programatically convert the remaining TIFFs to PDFs but they came out a little weird. For some reason, there is a small copy of each page right after the normal size copy of each page in the PDF (you'll see what I mean when you look at them). So, there's still a little fixing up to be done there. You can open them in Adobe and use the "Organize Pages" tool to delete the cover sheet and all of the copies of the other sheets, then add the accessibility components and upload to the folder linked previously in this ticket. I'll send you a link to the Box folder where I'm uploading the PDFs. Let me know if you have questions!

**Comment by madsmiller** [comment]
@emilyodean Got it! I see what you mean about the small copies. Thank you for converting them!

**Comment by madsmiller** [comment]
@emilyodean I completed 4384-4409 today. There were 3 that I have not done yet: 4402, 4403, and 4405. 4402 and 4403 appear to be multiple files in one PDF. I was going to ask you about that before moving forward.

**Comment by emilyodean** [comment]
@madsmiller emailed you about this as well, but will repeat here to track.

The PDFs with multiple files are what we call “multidistrict files.” It’s just one file, but we assign multiple ids – one for each district that is mentioned in the file – and create a cover sheet for each. Please just remove all the cover sheets at the beginning of those.

**Comment by madsmiller** [comment]
Completed 4412,4418,4420,4422,4426

**Comment by madsmiller** [comment]
Completed 4427 - 4452

**Comment by madsmiller** [comment]
Completed 4762-4769, 4846-4847

**Comment by madsmiller** [comment]
Completed 4770, 4840, 4848-4879

**Comment by madsmiller** [comment]
Completed 4841, 4879, 4880, 4889, 4890

**Comment by emilyodean** [comment]
Hi @madsmiller, I have some more TIFFs from the library that need to be converted to PDFs. I know you had some issues with programs crashing last time you tried to make the PDFs, so just keep track of which ones you are able to convert and which ones don't work, and I'll do the remaining ones. However, this time the TIFFs are not as well organized as last time. Unfortunately, they are not all in folders and none of them have IDs in their names. 

So, the task is to go through each folder within the "library_scans_raw" folder I'm about to share with you on Box, go through the Output subfolder, and sort the TIFFs into folders that are labeled by their IDs in the "library_scans" folder, which you already have access to. You can just "move" the TIFFs instead of copying them if permissions allow you to do so on Box. All of the scans are at least in order, so you'll just need to go through to find cover sheets and group with the subsequent pages before another cover sheet comes up. Don't worry about renaming the original TIFFs. Then, combine each into a PDF in the "library_scan_pdfs" folder. I do see that there is one folder called "box3-s1-rescan" within the "library_scans_raw" folder, so you will probably just want to cross-check those with the box3-s1 files and see if the rescans are better quality for that particular file.

After PDFing, you'll need to again make them accessible and then upload them to ResourceSpace.

Let me know if you have questions. Thanks!

**Comment by madsmiller** [comment]
Hi Emily,

This all sounds pretty straightforward. I started putting the first sets of
files into their own folders already. I noticed that some do not have
files/metadata uploaded into the collections website yet. Would you like me
to just look at the files after I have converted them to PDFs and then just
create and upload metadata for them? Also, I noticed that a majority of
these files are super long and thus have 2 or more IDs associated with
them. For example, 60004852, 60004853, and 60004854 are for the Geochemical
Reconnaissance of the Cortez-Buckhorn Area, Southern Cortez Mountains,
Nevada. For these, should I just create/upload three different files on the
collections website (so that each number is searchable) and just enter the
same information for each or should I just upload the first file ID and
mention the other two in the notes? I'm just curious as to how you would
like me to go about this.

Thanks,
Mads

**Comment by emilyodean** [comment]
@madsmiller I'm guessing that none of the scans that the library did have associated metadata in ResourceSpace already. They should all be in the mining district files spreadsheet that we need to load into ResourceSpace. For now, go ahead and just save the PDFs back to Box after making them accessible, and I'll try to port in all of the matching records when I get back from my vacation. Let's also wait until I'm back to have you drop off the box of files you've entered. 

For the files with multiple IDs, you'll save them under the first ID, and we'll use the other two IDs as reference. These are the "multi-district" files, so each ID refers to one district that is referenced. However, the record only needs to exist in ResourceSpace once (I will actually add a field in resourcespace called "multidistrict" to enter the other ids).

I'll be out of town today-next Wednesday but will be working remote next Tuesday in case you have questions.

**Comment by madsmiller** [comment]
@emilyodean Okay, wonderful! Sounds like I'm getting a little ahead of myself. For now I'll just continue to separate the files into their respective folders, converting them, and then making them accessible. Thanks for the info! I hope you have a great trip and I'll catch up with you soon.
