### ISSUE TITLE
2019 NGGDPP Mining District File online QA

### ISSUE THREAD

**Issue by emilyodean** [NBMG-UNR/gbssrl_students#4]
Go through all of the MD files that were scanned in FY 2019. Check that the online link works and that the PDF matches the original document.

**Comment by madsmiller** [comment]
Here are the inaccessible links thus far:
http://data.nbmg.unr.edu/Public/MiningDistricts/5040/60007497.pdf
--
http://data.nbmg.unr.edu/Public/MiningDistricts/5040/60007498.pdf
http://data.nbmg.unr.edu/Public/MiningDistricts/5040/60007499.pdf
http://data.nbmg.unr.edu/Public/MiningDistricts/5040/60007500.pdf

**Comment by emilyodean** [comment]
Noting here to keep a record - these links were broken because they were cross-referenced, and so the district folders were incorrect. For a temporary fix, I copied the files into both folders. This should probably be remedied with the next grant cycle, as it would be challenging to update content in all locations that it exists (webapps, NDC) at this time. 

I ran a link checker to identify other broken links. Will investigate and update if it is the same issue for all. 

- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/4060/60003737.pdf - Folder was not created, I created the folder and moved the document
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/0030/60003776.pdf - this link is incorrect, it should be in district 2470
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/1140/60003820pdf - link is incorrect, needs a period in the filename
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/3790/60003950.pdf - Incorrect district, should be 4740
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/2740/60004316.pdf - Incorrect district, should be 2730
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/2500/60004560.pdf - The ID in this link is incorrect for this record - should be 60004610
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/3370/60004561.pdf - The ID in this link is incorrect for this record, should be 60004611
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/2940/60004562.pdf - ID in the link was incorrect, should have been 4612
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/0930/60004563.pdf - ID incorrect, should have been 4613
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/2970/60006357.pdf - File was not in the folder on /web
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/2660/60006362.pdf - File was not in folder
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/3320/60007704.pdf - Wrong ID, should have been 7703
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/4770/60007705.pdf - Wrong ID, should have been 7704
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/1800/60007694.pdf - Multidistrict, needed to point to 5420
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/1800/60007731.pdf - multidistrict, needed to point to 5420
- [x] http://data.nbmg.unr.edu/Public/MiningDistricts/1030/60007731.pdf - multidistrict, needed to point to 5420

**Comment by emilyodean** [comment]
We're changing the QA method to spot check ~50 documents against the online version. If there are any glaring issues or major differences then we will increase that scope. We will also click the link to each document to make sure all the dead links were captured in the list above, and to do a cursory glance and make sure the documents load and look ok.

**Comment by emilyodean** [comment]
[mining_district_files_10222019_QA_12062019.xlsx](https://github.com/NBMG-UNR/gbssrl_students/files/3945913/mining_district_files_10222019_QA_12062019.xlsx)

**Comment by emilyodean** [comment]
Note that all of the above errors have been fixed in mining_district_files_12132019.csv. I am going to close this issue for now.
