### ISSUE TITLE
Accessible NBMG PDFs

### ISSUE THREAD

**Issue by emilyodean** [NBMG-UNR/gbssrl_students#9]
Resource: https://www.unr.edu/accessibility/documents/pdf

Use Adobe's tools to make the following PDFs accessible. 

[pub_sales_pdfs.xlsx](https://github.com/NBMG-UNR/gbssrl_students/files/3974724/pub_sales_pdfs.xlsx)

**Comment by emilyodean** [comment]
Start with the below: 

http://pubs.nbmg.unr.edu/Earthquakes-in-Nevada-and-how-t-p/e016.htm
http://pubs.nbmg.unr.edu/Terremotos-en-Nevada-y-como-sob-p/e027.htm
http://pubs.nbmg.unr.edu/Living-with-earthquakes-in-NV-p/sp027.htm
http://pubs.nbmg.unr.edu/Planning-scenario-for-major-EQ-p/sp020.htm
http://pubs.nbmg.unr.edu/Radon-in-Nevada-p/b108.htm

**Comment by emilyodean** [comment]
Please also do the following: 

http://pubs.nbmg.unr.edu/The-NV-mineral-industry-2017-p/mi2017.htm
https://pubs.nbmg.unr.edu/Turquoise-deposits-of-NV-p/r017.htm
https://pubs.nbmg.unr.edu/The-great-Highway-50-rock-tour-p/e044.htm
https://pubs.nbmg.unr.edu/Generalized-geologic-map-of-Nev-p/e030.htm - this one is going to be a little tricky but just do your best
https://pubs.nbmg.unr.edu/NV-active-mines-and-energy-2019-p/of2019-01.htm - same as above, slightly weird to try to remediate maps but just do your best
https://pubs.nbmg.unr.edu/Geol-map-of-Lahontan-Mts-quad-p/m168.htm
https://pubs.nbmg.unr.edu/Mining-claim-procedures-for-NV-p/sp006.htm
http://pubs.nbmg.unr.edu/Mining-districts-NV-2nd-ed-p/r047.htm
http://pubs.nbmg.unr.edu/Geol-terrane-map-NV-2-plates-p/of2010-04.htm

Also do go through the first spreadsheet linked in the comment above (pub_sales_pdfs.xlsx) and see what you can do with those geologic maps. It's really really hard to provide an equitable experience for people with limited sight for geologic maps, but if you can add some alternative text for the map image and tag the structure for the rest of the map, it might be a good first step.

**Comment by lweeks20** [comment]
This paper doesn't have a pdf attached to it
http://pubs.nbmg.unr.edu/Radon-in-Nevada-p/b108.htm

**Comment by emilyodean** [comment]
@lweeks20 that's fine, ignore that one in that case.

**Comment by lweeks20** [comment]
This document keeps making my acrobat crash so I will try it later in the day, however, all of the other documents have been uploaded to the box file
http://pubs.nbmg.unr.edu/Geol-terrane-map-NV-2-plates-p/of2010-04.htm

**Comment by emilyodean** [comment]
Sounds good, you can close this issue after you get that last one done. I'll probably need to reopen it and have you just do a couple of documents every once in awhile, but this is a great start for now.

**Comment by emilyodean** [comment]
@lweeks20 for the Radon one (http://pubs.nbmg.unr.edu/Radon-in-Nevada-p/b108.htm) the PDF is under the "free downloads" tab at the bottom of the page.

**Comment by lweeks20** [comment]
I got as far as I can with the file which is giving me problems. Everything is good to go except for when I try to verify it as an image only pdf.

**Comment by emilyodean** [comment]
@lweeks20 as mentioned yesterday, please try to do a handful of PDFs every time you come in (maybe spend an hour or so of your workday on this). I've uploaded a lot of PDFs to the box folder. Start with all  of the files that are in "sp" - https://nevada.app.box.com/folder/100931694963.

**Comment by emilyodean** [comment]
@lweeks20 please make this your priority this week and spend most of your workday on this. Our accessibility deadline is coming up. I need to be on campus all week this week, so please work at GBSSRL tomorrow, and then you can work remotely on Thursday if you want. 

Start with the freedownloads/of folder, and start with the ones dated the most recently. There are multiple PDFs in each zipped file, so once you correct them please re-zip them into a folder and upload it to the PDF_done folder. 

Let me know if you have questions.

**Comment by lweeks20** [comment]
All of the r files are complete

**Comment by lweeks20** [comment]
@emilyodean

**Comment by emilyodean** [comment]
@madsmiller I'm going to have you work on this as well. We'll have you start on the geospatial pdfs in the box folder that I just send to you. We'll chat when you get in today.
